---
title: "hw1"
author: "Evgeniy Glazunov"
date: '6 февраля 2018 г '
output: html_document
---

### 1.1
```{r}
library (tidyverse)
df1 <- read.csv("https://raw.githubusercontent.com/agricolamz/2018_data_analysis_for_linguists/master/data/students/dkbrz/hw1_agreement/hw1_1_zilo_class.csv", encoding = 'UTF-8')
as_tibble(df1)%>%
  group_by(stimulus_source) %>% 
  summarise(n = n_distinct(stimulus))
```
### 1.2
```{r}
library(irr)
df1 %>% 
  select(s_id, stimulus, translation_ru, stimulus_source, class) %>% 
  spread(key = s_id, value = class) ->
  zilo_classes_short
head(zilo_classes_short)
agree(zilo_classes_short[,-c(1:3)])
```
### 1.3
```{r}
zilo_classes_2s <- zilo_classes_short[,c(10, 14)]
agree(zilo_classes_2s)
kappa2(zilo_classes_2s)
```

### 1.4

```{r}
kappam.fleiss(zilo_classes_short[,-c(1:3)])
```


### 2.1
```{r}
df2 <- read_csv("https://raw.githubusercontent.com/agricolamz/2018_data_analysis_for_linguists/master/data/students/dkbrz/hw1_agreement/hw1_2_verbs.csv")
as_tibble(df2)%>%
  summarise(n = n_distinct(SubjectCode))
```

### 2.2
```{r}
as_tibble(df2)%>%
  group_by(WordType, Gender)%>%
  summarise(mean = mean(GivenScore))
```

### 2.3
```{r}
w <- na.omit(df2)
df2 %>% 
  select(Stimulus, SubjectCode, GivenScore) %>% 
  spread(key = SubjectCode, value = GivenScore) ->
  df2_short
head(zilo_classes_short)
df2_short <- na.omit(df2_short)
agree(df2_short[,-c(1)])
```
### 2.4
```{r}
kappam.fleiss(df2_short[,-c(1)])
```

### 2.5
```{r}
icc(df2_short[,-c(1)], model = "twoway", type = "agreement")
```

### 2.6
```{r}
w <- data.frame(cor(df2_short[, -1], method = "kendall"))
diag(w) <- NA
tibble(max = max(w, na.rm = TRUE), min = min(w, na.rm = TRUE))
```